"""
make_mechanics_ref.py — Generate a mechanics reference for a set review.

Reads the set's card CSV to detect which keywords, ability words, and special
layouts are present. Extracts the relevant rule text from the downloaded
comprehensive rules and writes a concise reference for evaluation agents.

Usage (from deq/):
  pdm run python scripts/make_mechanics_ref.py --set SOS

Requires:
  ~/dev/set-reviews/{SET}_cards.csv   (generated by make_card_csv.py)
  ~/dev/set-reviews/MagicCompRules.txt (downloaded by update_rules.py)

Output:
  ~/dev/set-reviews/{SET}_mechanics.txt
"""

import argparse
import csv
import re
import sys
from pathlib import Path

SET_REVIEWS = Path.home() / "dev" / "set-reviews"
COMP_RULES = SET_REVIEWS / "MagicCompRules.txt"

# Ability words have no comp rules entry; defined entirely by card text (rule 207.2c).
KNOWN_ABILITY_WORDS = {
    "alliance", "battalion", "bloodrush", "celebration", "channel", "chroma",
    "cohort", "constellation", "converge", "coven", "delirium", "domain",
    "eerie", "eminence", "enrage", "fateful hour", "ferocious", "formidable",
    "grandeur", "hellbent", "heroic", "infusion", "inspired", "kinship",
    "landfall", "lieutenant", "magecraft", "metalcraft", "morbid", "opus",
    "paradox", "parley", "raid", "rally", "repartee", "revolt",
    "spell mastery", "strive", "survival", "sweep", "threshold",
    "undergrowth", "valiant",
}

# Well-known keywords — agents already understand these; no need for rule excerpts.
# They'll be listed in a "common keywords" footer line rather than extracted.
EVERGREEN_KEYWORDS = {
    "annihilator", "battle cry", "bestow", "bloodthirst", "bolster", "boast",
    "bushido", "buyback", "cascade", "casualty", "champion", "cipher",
    "cleave", "connive", "convoke", "crew", "cycling", "dash", "daybound",
    "deathtouch", "defender", "delve", "double strike", "dredge",
    "echo", "enchant", "enlist", "equip", "escape", "evoke", "evolve",
    "exalted", "exploit", "extort", "fabricate", "fading", "first strike",
    "flanking", "flash", "flashback", "flying", "foretell", "fortify",
    "frenzy", "goad", "gravestorm", "haste", "haunt", "hexproof",
    "hideaway", "horsemanship", "improvise", "indestructible", "infect",
    "investigate", "jump-start", "kicker", "landwalk", "learn", "level up",
    "lifelink", "living weapon", "madness", "menace", "mentor", "melee",
    "miracle", "modular", "monstrosity", "morph", "myriad", "ninjutsu",
    "offering", "outlast", "overload", "partner", "persist", "phasing",
    "plainswalk", "populate", "proliferate", "prototype", "provoke",
    "prowl", "rampage", "reach", "rebound", "reconfigure", "recover",
    "reinforce", "renown", "replicate", "retrace", "riot", "ripple",
    "saddle", "scavenge", "shadow", "shroud", "skulk", "soulbond",
    "soulshift", "spectacle", "splice", "split second", "storm",
    "sunburst", "support", "surge", "suspend", "totem armor", "trample",
    "transfigure", "transmute", "tribute", "undaunted", "undying",
    "unearth", "unleash", "vanishing", "vigilance", "ward", "wither",
}

# Multi-face layouts and which rule section covers them.
LAYOUT_RULES = {
    "prepare": "722",
    "adventure": "715",
    "transform": "712",
    "modal_dfc": "712",
    "split": "709",
    "flip": "710",
}

LAYOUT_TITLES = {
    "prepare": "Preparation Cards",
    "adventure": "Adventure Cards",
    "transform": "Transform Double-Faced Cards",
    "modal_dfc": "Modal Double-Faced Cards",
    "split": "Split Cards",
    "flip": "Flip Cards",
}

LAYOUT_DESCRIPTIONS = {
    "prepare": (
        "When a creature 'enters prepared,' a copy of its PREPARE SPELL is created in exile."
        " The controller may cast that copy for FREE (no mana cost). Casting it removes the"
        " prepared designation. The printed cost on the prepare spell only matters for effects"
        " that care about mana value — you always cast it for free.\n"
        "Key for evaluation: a 1/1 for {W} that 'enters prepared' is a 1/1 PLUS whatever the"
        " free spell does. The spell is the main payoff; the body is a bonus."
    ),
    "adventure": (
        "An Adventure card has two playable halves: a creature and an instant/sorcery (the"
        " adventure). Cast the adventure from hand first; it resolves, the card is exiled, and"
        " you may later cast the creature from exile. You get both effects from a single card —"
        " this is genuine two-for-one value.\n"
        "Key for evaluation: grade the combined value of both halves, not each half separately."
    ),
    "transform": (
        "A transform DFC has a front face and a back face. The creature/permanent can transform"
        " to its back face under certain conditions (usually triggered). Evaluate both faces when"
        " grading — the back face often has a substantially different power level."
    ),
    "modal_dfc": (
        "A modal DFC has two independently castable faces. You choose which face to cast when"
        " you play it. Evaluate on the flexibility of having two options from a single card slot."
    ),
}


def load_comp_rules() -> str:
    if not COMP_RULES.exists():
        raise FileNotFoundError(
            f"Comprehensive rules not found at {COMP_RULES}. "
            "Run: pdm run python scripts/update_rules.py"
        )
    return COMP_RULES.read_text(encoding="utf-8", errors="replace")


def find_rule_by_name(rules_text: str, keyword: str, max_lines: int = 12) -> str:
    """Find a keyword's rule section by searching for its name in the numbered rules.

    Looks for lines like '702.191. Increment' and extracts the section text.
    Falls back to the glossary if no numbered section is found.
    """
    lines = rules_text.splitlines()

    # Match section headings: "702.191. KeywordName" or "722. KeywordName"
    heading_re = re.compile(
        r"^(\d+(?:\.\d+)*)\.\s+" + re.escape(keyword) + r"\b",
        re.IGNORECASE,
    )

    start = -1
    cur_section_parts: list[int] = []
    for i, line in enumerate(lines):
        m = heading_re.match(line.strip())
        if m:
            start = i
            cur_section_parts = [int(p) for p in m.group(1).split(".")]
            break

    if start < 0:
        return _find_glossary_entry(rules_text, keyword)

    result = [lines[start].strip()]

    for i in range(start + 1, len(lines)):
        line = lines[i].strip()
        if not line:
            continue

        # Stop when we hit a new section at the same or higher level
        next_heading = re.match(r"^(\d+(?:\.\d+)*)\.", line)
        if next_heading:
            next_parts = [int(p) for p in next_heading.group(1).split(".")]
            # Compare at the level of the current section
            depth = len(cur_section_parts)
            next_at_depth = next_parts[:depth]
            cur_at_depth = cur_section_parts[:depth]
            if len(next_at_depth) == depth and next_at_depth > cur_at_depth:
                # Check it's not a deeper sub-section (702.191a format)
                # Those have letters after the number, not parsed here
                if not re.match(r"^\d+(?:\.\d+)*[a-z]", line):
                    break

        result.append(line)
        if len(result) >= max_lines:
            break

    return "\n".join(result)


def _find_glossary_entry(rules_text: str, term: str) -> str:
    """Find a term in the glossary section (fallback for find_rule_by_name)."""
    lines = rules_text.splitlines()
    in_glossary = False
    collecting = False
    result = []

    for line in lines:
        stripped = line.strip()
        if "Glossary" in stripped and not in_glossary and not collecting:
            in_glossary = True
            continue
        if not in_glossary:
            continue
        if not collecting:
            if stripped.lower() == term.lower():
                collecting = True
                result.append(stripped)
        else:
            if not stripped:
                break
            if len(stripped) < 60 and "." not in stripped and stripped[0].isupper():
                break
            result.append(stripped)
            if len(result) >= 5:
                break

    return "\n".join(result)


def detect_layouts(rows: list[dict]) -> set[str]:
    """Detect multi-face layouts from inline markers in oracle_text."""
    layouts: set[str] = set()
    for row in rows:
        oracle = (row.get("oracle_text") or "").lower()
        if "prepare spell —" in oracle or "enters prepared" in oracle:
            layouts.add("prepare")
        if "adventure:" in oracle:
            layouts.add("adventure")
        if "transforms into:" in oracle:
            layouts.add("transform")
        if "back face —" in oracle:
            layouts.add("modal_dfc")
    return layouts


def detect_keywords(oracle_all: str) -> tuple[list[str], list[str]]:
    """Return (novel_keywords, evergreen_keywords) detected in oracle text."""
    novel: list[str] = []
    evergreen: list[str] = []
    seen = set(KNOWN_ABILITY_WORDS)  # don't double-count ability words

    # Scan for keywords. Order matters: check multi-word first.
    all_keywords = sorted(
        set(EVERGREEN_KEYWORDS) | {kw for kw in _extra_keywords()},
        key=lambda k: -len(k),
    )

    for kw in all_keywords:
        if kw in seen:
            continue
        if re.search(r"\b" + re.escape(kw) + r"\b", oracle_all, re.IGNORECASE):
            seen.add(kw)
            if kw in EVERGREEN_KEYWORDS:
                evergreen.append(kw)
            else:
                novel.append(kw)

    return sorted(novel), sorted(evergreen)


def _extra_keywords() -> list[str]:
    """Additional known keywords not in EVERGREEN_KEYWORDS (newer/set-specific)."""
    return [
        "adapt", "amass", "augment", "backup", "blitz", "bolster", "boast",
        "casualty", "companion", "detain", "discover", "disturb", "encore",
        "exert", "fabricate", "foretell", "for mirrodin!", "fracture",
        "gifted", "impact", "increment", "intensify", "investigate",
        "learn", "mill", "mutate", "offering", "outlast", "populate",
        "proliferate", "prototype", "read ahead", "reconfigure", "riot",
        "saddle", "spectacle", "support", "training", "undaunted",
        "valiant", "ward",
    ]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--set", required=True, dest="set_code", metavar="SET")
    args = parser.parse_args()

    SET = args.set_code
    cards_path = SET_REVIEWS / f"{SET}_cards.csv"
    if not cards_path.exists():
        print(f"ERROR: Card CSV not found: {cards_path}", file=sys.stderr)
        print("Run: pdm run python scripts/make_card_csv.py --set " + SET, file=sys.stderr)
        sys.exit(1)

    try:
        rules = load_comp_rules()
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    with open(cards_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    full_oracle = " ".join((r.get("oracle_text") or "").lower() for r in rows)

    # Detect ability words
    ability_words_present = sorted(
        aw for aw in KNOWN_ABILITY_WORDS
        if re.search(r"\b" + re.escape(aw) + r"\b", full_oracle)
    )

    # Detect keywords
    novel_keywords, evergreen_kws = detect_keywords(full_oracle)

    # Detect multi-face layouts from inline markers
    layouts_present = detect_layouts(rows)

    # Build output
    out_lines = [f"# {SET} Mechanics Reference", ""]
    wrote_any = False

    # --- Multi-face cards ---
    if layouts_present:
        wrote_any = True
        out_lines.append("## Multi-Face Cards")
        out_lines.append(
            "Back-face oracle text is embedded inline in the card CSV, separated by ' || '."
            " The agent does not need to look up prepare spells, adventures, or back faces separately."
        )
        out_lines.append("")

        for layout in sorted(layouts_present):
            title = LAYOUT_TITLES.get(layout, layout.title())
            rule_section = LAYOUT_RULES.get(layout)
            heading = f"{title} (rule {rule_section})" if rule_section else title
            out_lines.append(f"### {heading}")

            desc = LAYOUT_DESCRIPTIONS.get(layout)
            if desc:
                out_lines.append(desc)
            out_lines.append("")

    # --- Novel keyword abilities ---
    if novel_keywords:
        wrote_any = True
        out_lines.append("## New or Set-Specific Keyword Abilities")
        out_lines.append("")

        for kw in novel_keywords:
            out_lines.append(f"### {kw.title()}")
            rule_text = find_rule_by_name(rules, kw.title())
            if not rule_text:
                rule_text = find_rule_by_name(rules, kw)
            if rule_text:
                out_lines.append(rule_text)
            else:
                out_lines.append("(No rule entry found — refer to card text.)")
            out_lines.append("")

    # --- Ability words ---
    if ability_words_present:
        wrote_any = True
        out_lines.append("## Ability Words")
        out_lines.append(
            "The following are ability words (rule 207.2c). They have no separate"
            " comprehensive rules entry — each card's oracle text fully defines the"
            " trigger condition and effect for that card. Read each card carefully;"
            " do not generalize the trigger condition across cards with the same word."
        )
        out_lines.append("")
        for aw in ability_words_present:
            out_lines.append(f"- **{aw.title()}**")
        out_lines.append("")
        out_lines.append(
            "Ability words are purely cosmetic labels — they mark a theme, but the"
            " actual rules are on the card."
        )
        out_lines.append("")

    # --- Common keywords footer ---
    if evergreen_kws:
        out_lines.append("## Common Keywords (no rules excerpt needed)")
        out_lines.append(
            "These keywords appear in the set but are well-known. Agents are assumed"
            " to understand them without additional rules text:"
        )
        out_lines.append("")
        out_lines.append(", ".join(kw.title() for kw in evergreen_kws) + ".")
        out_lines.append("")

    if not wrote_any:
        out_lines.append("(No set-specific mechanics detected.)")

    out_path = SET_REVIEWS / f"{SET}_mechanics.txt"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines))

    print(f"Wrote mechanics reference → {out_path}")
    if layouts_present:
        print(f"  Multi-face layouts: {', '.join(sorted(layouts_present))}")
    if novel_keywords:
        print(f"  Novel keywords (with rule excerpts): {', '.join(novel_keywords)}")
    if ability_words_present:
        print(f"  Ability words: {', '.join(ability_words_present)}")
    if evergreen_kws:
        print(f"  Common keywords (no excerpts): {', '.join(evergreen_kws)}")


if __name__ == "__main__":
    main()
